export const TURKEY_DATA: Record<string, string[]> = {
  "Adana": ["Seyhan", "Çukurova", "Sarıçam", "Yüreğir", "Ceyhan", "Kozan"],
  "Adıyaman": ["Merkez", "Kahta", "Besni", "Gölbaşı", "Gerger"],
  "Afyonkarahisar": ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Emirdağ"],
  "Ağrı": ["Merkez", "Patnos", "Doğubayazıt", "Diyadin", "Eleşkirt"],
  "Amasya": ["Merkez", "Merzifon", "Suluova", "Gümüşhacıköy"],
  "Ankara": ["Çankaya", "Keçiören", "Yenimahalle", "Mamak", "Etimesgut", "Sincan", "Gölbaşı"],
  "Antalya": ["Muratpaşa", "Kepez", "Konyaaltı", "Alanya", "Manavgat", "Serik", "Kemer"],
  "Artvin": ["Merkez", "Hopa", "Arhavi", "Borçka", "Murgul"],
  "Aydın": ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "Çine"],
  "Balıkesir": ["Karesi", "Altıeylül", "Bandırma", "Edremit", "Ayvalık", "Gönen"],
  "Bilecik": ["Merkez", "Bozüyük", "Osmaneli", "Söğüt"],
  "Bingöl": ["Merkez", "Genç", "Solhan", "Karlıova"],
  "Bitlis": ["Merkez", "Tatvan", "Ahlat", "Güroymak"],
  "Bolu": ["Merkez", "Gerede", "Mudurnu", "Mengen"],
  "Burdur": ["Merkez", "Bucak", "Gölhisar", "Tefenni"],
  "Bursa": ["Osmangazi", "Nilüfer", "Yıldırım", "İnegöl", "Gemlik", "Mudanya"],
  "Çanakkale": ["Merkez", "Biga", "Çan", "Gelibolu", "Ayvacık"],
  "Çankırı": ["Merkez", "Çerkeş", "Ilgaz", "Eldivan"],
  "Çorum": ["Merkez", "Sungurlu", "Osmancık", "İskilip"],
  "Denizli": ["Pamukkale", "Merkezefendi", "Acıpayam", "Tavas", "Honaz"],
  "Diyarbakır": ["Bağlar", "Kayapınar", "Yenişehir", "Sur", "Ergani", "Bismil"],
  "Edirne": ["Merkez", "Keşan", "Uzunköprü", "İpsala"],
  "Elazığ": ["Merkez", "Kovancılar", "Karakoçan", "Palu"],
  "Erzincan": ["Merkez", "Tercan", "Üzümlü", "Refahiye"],
  "Erzurum": ["Yakutiye", "Palandöken", "Aziziye", "Oltu", "Pasinler"],
  "Eskişehir": ["Odunpazarı", "Tepebaşı", "Sivrihisar", "Çifteler"],
  "Gaziantep": ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Oğuzeli"],
  "Giresun": ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu"],
  "Gümüşhane": ["Merkez", "Kelkit", "Şiran", "Kürtün"],
  "Hakkari": ["Merkez", "Yüksekova", "Şemdinli", "Çukurca"],
  "Hatay": ["Antakya", "İskenderun", "Defne", "Dörtyol", "Samandağ", "Kırıkhan"],
  "Isparta": ["Merkez", "Eğirdir", "Şarkikaraağaç", "Gelendost"],
  "Mersin": ["Yenişehir", "Mezitli", "Toroslar", "Akdeniz", "Tarsus", "Silifke", "Anamur"],
  "İstanbul": ["Beşiktaş", "Kadıköy", "Şişli", "Üsküdar", "Esenyurt", "Bakırköy", "Beylikdüzü"],
  "İzmir": ["Konak", "Karşıyaka", "Bornova", "Buca", "Çiğli", "Torbalı", "Menemen"],
  "Kars": ["Merkez", "Kağızman", "Sarıkamış", "Digor"],
  "Kastamonu": ["Merkez", "Tosya", "Taşköprü", "İnebolu"],
  "Kayseri": ["Melikgazi", "Kocasinan", "Talas", "Develi", "Yahyalı"],
  "Kırklareli": ["Merkez", "Lüleburgaz", "Babaeski", "Vize"],
  "Kırşehir": ["Merkez", "Kaman", "Mucur", "Çiçekdağı"],
  "Kocaeli": ["İzmit", "Gebze", "Gölcük", "Körfez", "Derince", "Kartepe"],
  "Konya": ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Seydişehir", "Beyşehir"],
  "Kütahya": ["Merkez", "Tavşanlı", "Simav", "Gediz"],
  "Malatya": ["Yeşilyurt", "Battalgazi", "Doğanşehir", "Akçadağ"],
  "Manisa": ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Soma", "Salihli"],
  "Kahramanmaraş": ["Onikişubat", "Dulkadiroğlu", "Elbistan", "Afşin", "Pazarcık"],
  "Mardin": ["Artuklu", "Kızıltepe", "Nusaybin", "Midyat", "Derik"],
  "Muğla": ["Menteşe", "Bodrum", "Fethiye", "Marmaris", "Milas", "Ortaca"],
  "Muş": ["Merkez", "Bulanık", "Malazgirt", "Varto"],
  "Nevşehir": ["Merkez", "Ürgüp", "Avanos", "Gülşehir"],
  "Niğde": ["Merkez", "Bor", "Çamardı", "Ulukışla"],
  "Ordu": ["Altınordu", "Ünye", "Fatsa", "Kumru"],
  "Rize": ["Merkez", "Çayeli", "Ardeşen", "Pazar", "Güneysu"],
  "Sakarya": ["Adapazarı", "Serdivan", "Erenler", "Akyazı", "Hendek", "Karasu"],
  "Samsun": ["İlkadım", "Atakum", "Canik", "Bafra", "Çarşamba", "Vezirköprü"],
  "Siirt": ["Merkez", "Kurtalan", "Baykan", "Eruh"],
  "Sinop": ["Merkez", "Boyabat", "Gerze", "Ayancık"],
  "Sivas": ["Merkez", "Şarkışla", "Yıldızeli", "Suşehri", "Gemerek"],
  "Tekirdağ": ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Kapaklı", "Ergene"],
  "Tokat": ["Merkez", "Erbaa", "Turhal", "Zile", "Niksar"],
  "Trabzon": ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra", "Arsin"],
  "Tunceli": ["Merkez", "Pertek", "Mazgirt", "Çemişgezek"],
  "Şanlıurfa": ["Eyyübiye", "Haliliye", "Karaköprü", "Siverek", "Viranşehir", "Suruç"],
  "Uşak": ["Merkez", "Banaz", "Eşme", "Sivaslı"],
  "Van": ["İpekyolu", "Tuşba", "Edremit", "Erciş", "Gevaş", "Özalp"],
  "Yozgat": ["Merkez", "Sorgun", "Akdağmadeni", "Yerköy"],
  "Zonguldak": ["Merkez", "Ereğli", "Çaycuma", "Devrek", "Kozlu"],
  "Aksaray": ["Merkez", "Eskil", "Ortaköy", "Gülağaç"],
  "Bayburt": ["Merkez", "Aydıntepe", "Demirözü"],
  "Karaman": ["Merkez", "Ermenek", "Sarıveliler", "Kazımkarabekir"],
  "Kırıkkale": ["Merkez", "Yahşihan", "Keskin", "Delice"],
  "Batman": ["Merkez", "Kozluk", "Sason", "Beşiri"],
  "Şırnak": ["Merkez", "Cizre", "Silopi", "İdil", "Uludere"],
  "Bartın": ["Merkez", "Amasra", "Ulus", "Kurucaşile"],
  "Ardahan": ["Merkez", "Göle", "Çıldır", "Hanak"],
  "Iğdır": ["Merkez", "Tuzluca", "Aralık", "Karakoyunlu"],
  "Yalova": ["Merkez", "Çiftlikköy", "Çınarcık", "Altınova"],
  "Karabük": ["Merkez", "Safranbolu", "Yenice", "Eskipazar"],
  "Kilis": ["Merkez", "Musabeyli", "Elbeyli", "Polateli"],
  "Osmaniye": ["Merkez", "Kadirli", "Düziçi", "Bahçe"],
  "Düzce": ["Merkez", "Akçakoca", "Kaynaşlı", "Çilimli"]
};